// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_3Fd1ttYYZlFFFxMnv1J5ngKu9Axh-Ac',
    appId: '1:963237383868:web:79048f4bdbeaf1f7358ab9',
    messagingSenderId: '963237383868',
    projectId: 'fyp-project-a9b28',
    authDomain: 'fyp-project-a9b28.firebaseapp.com',
    storageBucket: 'fyp-project-a9b28.firebasestorage.app',
    measurementId: 'G-QE6KCC5XD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYLqnqCaqP5lCxGAe5Sa0Z6WJ6aNl_Uwg',
    appId: '1:963237383868:android:fe0f38a84141f423358ab9',
    messagingSenderId: '963237383868',
    projectId: 'fyp-project-a9b28',
    storageBucket: 'fyp-project-a9b28.firebasestorage.app',
  );
}
